site_name: Astronáutica

theme:
  name: material
  language: es
  icon:
    logo: fontawesome/solid/rocket
  palette:
    primary: amber
    accent: deep purple
  font:
    text: Futura
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
    - header.autohide
    - navigation.indexes
    - navigation.footer
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TiramisudeAgras/Astronautica
      name: Repositorio de Astronáutica

copyright: Copyright &copy; 2023 Santiago Acuña González

nav:
    - Inicio: index.md
    - Códigos & Scripts:
      - codigo & scripts/index.md
      - Código 4.1: codigo & scripts/codigo4.1.md
      - Código 4.2: codigo & scripts/codigo4.2.md

plugins:
  - search:
      lang:
        - es
        - en
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

